project:
  type: book
  preview:
    port: 4400
    browser: true

book:
  title: "Designing a Course With Quarto"
  author: "Nakul R. Padalkar"
  date: "12/9/2025"
  date-format: long
  chapters:
    - href: index.qmd
      text: "Introduction"
    - href: 02_professor_quickstart.qmd
      text: "Professor Quickstart"
    - href: 03_tool_setup.qmd
      text: "Tool Setup"
    - href: 04_version_control.qmd
      text: "Git and GitHub"
    - href: 05_working_with_quarto.qmd
      text: "Working with Quarto"
    - href: 06_creating_excel.qmd
      text: "Creating Excel Files"
    - href: 07_quarto_class_setup.qmd
      text: "Quarto Class Setup"
    - href: 08_github_classroom.qmd
      text: "GitHub Classroom"
    - href: 09_cloud_analytics_with_aws.qmd
      text: "Cloud Analytics with AWS"
    - href: 10_blackboard_ultra.qmd
      text: "Blackboard Ultra"
    - href: 11_automating_with_AI.qmd
      text: "Automating with AI"
    - href: 12_capstone_build_like_ad688.qmd
      text: "Build a Course Like AD688"
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
    - cosmo
    - ./theme/book.scss
    code-overflow: wrap
    embed-resources: false
    fontawesome: true

execute:
  freeze: false
  cache: false

